tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e0e3e5",
        "outline-variant": "#c7c4d8",
        "on-secondary": "#ffffff",
        "surface-tint": "#4d44e3",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#004c6e",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "primary-container": "#4f46e5",
        "on-tertiary-container": "#b8e0ff",
        "surface-bright": "#f7f9fb",
        surface: "#f7f9fb",
        background: "#f7f9fb",
        "on-secondary-fixed-variant": "#2f2ebe",
        "inverse-on-surface": "#eff1f3",
        primary: "#3525cd",
        "on-surface-variant": "#464555",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#dad7ff",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed-dim": "#89ceff",
        error: "#ba1a1a",
        "primary-fixed-dim": "#c3c0ff",
        outline: "#777587",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-fixed": "#001e2f",
        "primary-fixed": "#e2dfff",
        "on-background": "#191c1e",
        secondary: "#4648d4",
        "on-secondary-fixed": "#07006c",
        "tertiary-container": "#006693",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#c9e6ff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#fffbff",
        "on-primary-fixed": "#0f0069",
        "surface-container": "#eceef0",
        "secondary-fixed": "#e1e0ff",
        "inverse-primary": "#c3c0ff",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        tertiary: "#004d70",
        "secondary-fixed-dim": "#c0c1ff",
        "secondary-container": "#6063ee",
        success: "#1e8e3e",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        display: ["Geist", "sans-serif"],
      },
    },
  },
};
