tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#004d70",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#c3c0ff",
        "primary-container": "#4f46e5",
        "tertiary-fixed-dim": "#89ceff",
        "surface-container-highest": "#e0e3e5",
        surface: "#f7f9fb",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#006693",
        "secondary-fixed-dim": "#c0c1ff",
        "surface-tint": "#4d44e3",
        "inverse-primary": "#c3c0ff",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#004c6e",
        "on-primary-container": "#dad7ff",
        "on-secondary-fixed": "#07006c",
        "tertiary-fixed": "#c9e6ff",
        primary: "#3525cd",
        outline: "#777587",
        "on-tertiary-container": "#b8e0ff",
        "surface-container-high": "#e6e8ea",
        "surface-container": "#eceef0",
        "on-surface": "#191c1e",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "inverse-on-surface": "#eff1f3",
        "secondary-container": "#6063ee",
        "primary-fixed": "#e2dfff",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-low": "#f2f4f6",
        secondary: "#4648d4",
        "outline-variant": "#c7c4d8",
        "error-container": "#ffdad6",
        "on-surface-variant": "#464555",
        background: "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "on-tertiary-fixed": "#001e2f",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#e1e0ff",
        "on-error": "#ffffff",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        gutter: "24px",
        base: "4px",
        md: "1.5rem",
        lg: "2rem",
        xs: "0.5rem",
        sm: "1rem",
        xl: "3rem",
      },
      fontFamily: {
        "label-sm": ["Geist"],
        "label-md": ["Geist"],
        "headline-md": ["Geist"],
        "body-md": ["Geist"],
        "body-lg": ["Geist"],
        "headline-lg": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        display: ["Geist"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        display: [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
};
